/**
 * Definitions for every image produced by the main integration fixture build.
 *
 * Each entry describes:
 *   - which Astro page to screenshot (`page`)
 *   - the configuration to pass to the snapshot integration (`screenshotConfig`)
 *   - the properties the resulting image is expected to have (`expected`)
 *
 * @module
 */

import { join } from 'node:path';
import type sharp from 'sharp';
import type { Config } from '../packages/astro-snapshot/src/index.ts';

/**
 * A color in the format `{ r: number, g: number, b: number }`.
 */
export type Color = sharp.Stats['dominant'];

/**
 * Properties an output image is expected to have.
 */
interface ImageExpectation {
	format: string;
	width: number;
	height: number;
	color: Color;
}

interface FixtureImage {
	/** Astro page route to screenshot. */
	readonly page: string;
	/** Config entry passed to the snapshot integration (includes `outputPath`). */
	readonly screenshotConfig: Config['pages'][string][number];
	/** Properties the produced image is expected to have. If undefined, no assertions are made (useful for setup). */
	readonly expected?: ImageExpectation;
}

/** Directory (relative to the fixture project root) where all test outputs land. */
export const OUTPUT_DIR = 'output' as const;

export const RED: Color = {
	r: 255,
	g: 0,
	b: 0,
};

export const GREEN: Color = {
	r: 0,
	g: 255,
	b: 0,
};

/**
 * Default page path for all tests.
 */
const DEFAULT_PAGE_PATH = '/red' as const;

/**
 * Output subdirectory for the shared build.
 */
const SHARED_OUTPUT_DIR = join(OUTPUT_DIR, 'shared');

/**
 * Default image expectations for all tests.
 *
 * This is what the integration should fall back to.
 */
const DEFAULT_EXPECTED = {
	format: 'png',
	width: 1200,
	height: 630,
	color: RED,
} as const;

/**
 * Test cases for `overwrite: false`.
 */
const OVERWRITE_SKIP_TEST_CASES: Record<string, FixtureImage> = {
	// 1. Set up the test by generating a red image.
	'[setup] overwrite disabled': {
		page: DEFAULT_PAGE_PATH,
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/overwrite-disabled.png`,
		},
	},
	// 2. The second write should skip because overwrite is false.
	'overwrite disabled': {
		page: '/green',
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/overwrite-disabled.png`,
		},
		// The image should still be red
		expected: DEFAULT_EXPECTED,
	},
};

/**
 * Test cases for `overwrite: true`.
 */
const OVERWRITE_REPLACE_TEST_CASES: Record<string, FixtureImage> = {
	// 1. Set up the test by generating a red image.
	'[setup] overwrite enabled': {
		page: DEFAULT_PAGE_PATH,
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/overwrite-enabled.png`,
		},
	},
	// 2. The second write should replace the image because overwrite is true.
	'overwrite enabled': {
		page: '/green',
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/overwrite-enabled.png`,
			overwrite: true,
		},
		expected: {
			...DEFAULT_EXPECTED,
			// The image should now be green
			color: GREEN,
		},
	},
};

/**
 * All images generated by the main fixture build (`astro.config.ts`).
 *
 * Keys are used as human-readable labels in test output.
 */
export const TEST_CASES: Record<string, FixtureImage> = {
	// With no width/height set, the integration should fall back to the default values.
	'bare bones': {
		page: DEFAULT_PAGE_PATH,
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/bare-bones.png`,
		},
		expected: DEFAULT_EXPECTED,
	},
	// Provided width should override the default.
	'width': {
		page: DEFAULT_PAGE_PATH,
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/width.png`,
			width: 80,
		},
		expected: {
			...DEFAULT_EXPECTED,
			width: 80,
		},
	},
	// Provided height should override the default.
	'height': {
		page: DEFAULT_PAGE_PATH,
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/height.png`,
			height: 40,
		},
		expected: {
			...DEFAULT_EXPECTED,
			height: 40,
		},
	},
	// Provided width and height should override the defaults.
	'width & height': {
		page: DEFAULT_PAGE_PATH,
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/width-and-height.png`,
			width: 80,
			height: 40,
		},
		expected: {
			...DEFAULT_EXPECTED,
			width: 80,
			height: 40,
		},
	},
	// A .png extension should result in a PNG screenshot.
	'.png extension': {
		page: DEFAULT_PAGE_PATH,
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/format.png`,
		},
		expected: {
			...DEFAULT_EXPECTED,
			format: 'png',
		},
	},
	// A .jpg extension should result in a JPEG screenshot.
	'.jpg extension': {
		page: DEFAULT_PAGE_PATH,
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/format.jpg`,
		},
		expected: {
			...DEFAULT_EXPECTED,
			format: 'jpeg',
		},
	},
	// A .jpeg extension should result in a JPEG screenshot.
	'.jpeg extension': {
		page: DEFAULT_PAGE_PATH,
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/format.jpeg`,
		},
		expected: {
			...DEFAULT_EXPECTED,
			format: 'jpeg',
		},
	},
	// A .webp extension should result in a WebP screenshot.
	'.webp extension': {
		page: DEFAULT_PAGE_PATH,
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/format.webp`,
		},
		expected: {
			...DEFAULT_EXPECTED,
			format: 'webp',
		},
	},
	...OVERWRITE_SKIP_TEST_CASES,
	...OVERWRITE_REPLACE_TEST_CASES,
	// A deviceScaleFactor of 2 should result in a screenshot that is twice as large.
	'deviceScaleFactor viewport option': {
		page: DEFAULT_PAGE_PATH,
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/viewport-device-scale-factor.png`,
			width: 600,
			height: 315,
			setViewportOptions: {
				deviceScaleFactor: 2,
			},
		},
		expected: DEFAULT_EXPECTED,
	},
	// A page key without a leading '/' should be normalized
	'page path normalization': {
		page: 'red',
		screenshotConfig: {
			outputPath: `${SHARED_OUTPUT_DIR}/path-normalization.png`,
		},
		expected: DEFAULT_EXPECTED,
	},
};
