/**
 * Definitions for every image produced by the main integration fixture build.
 *
 * Each entry describes:
 *   - which Astro page to screenshot (`page`)
 *   - the configuration to pass to the snapshot integration (`screenshotConfig`)
 *   - the properties the resulting image is expected to have (`expected`)
 *
 * @module
 */

import type sharp from 'sharp';
import type { Config } from '../packages/astro-snapshot/src/index.ts';

/**
 * A color in the format `{ r: number, g: number, b: number }`.
 */
export type Color = sharp.Stats['dominant'];

export interface ImageExpectation {
	format: string;
	width: number;
	height: number;
	color?: Color;
}

export interface FixtureImage {
	/** Astro page route to screenshot. */
	readonly page: string;
	/** Config entry passed to the snapshot integration (includes `outputPath`). */
	readonly screenshotConfig: Config['pages'][string][number];
	/** Properties the produced image is expected to have. */
	readonly expected: ImageExpectation;
}

/** Directory (relative to the fixture project root) where all test outputs land. */
export const OUTPUT_DIR = 'output' as const;

export const RED: Color = {
	r: 255,
	g: 0,
	b: 0,
};

/**
 * Default image expectations for all tests.
 *
 * This is what the integration should fall back to.
 */
const DEFAULT_EXPECTED = {
	format: 'png',
	width: 1200,
	height: 630,
	color: RED,
};

/**
 * All images generated by the main fixture build (`astro.config.ts`).
 *
 * Keys are used as human-readable labels in test output.
 */
export const IMAGES = {
	// With no width/height set, the integration should fall back to the default values.
	'bare bones': {
		page: '/',
		screenshotConfig: {
			outputPath: `${OUTPUT_DIR}/bare-bones.png`,
		},
		expected: DEFAULT_EXPECTED,
	},
	// Provided width should override the default.
	'width': {
		page: '/',
		screenshotConfig: {
			outputPath: `${OUTPUT_DIR}/width.png`,
			width: 80,
		},
		expected: {
			...DEFAULT_EXPECTED,
			width: 80,
		},
	},
	// Provided height should override the default.
	'height': {
		page: '/',
		screenshotConfig: {
			outputPath: `${OUTPUT_DIR}/height.png`,
			height: 40,
		},
		expected: {
			...DEFAULT_EXPECTED,
			height: 40,
		},
	},
	// Provided width and height should override the defaults.
	'width & height': {
		page: '/',
		screenshotConfig: {
			outputPath: `${OUTPUT_DIR}/width-and-height.png`,
			width: 80,
			height: 40,
		},
		expected: {
			...DEFAULT_EXPECTED,
			width: 80,
			height: 40,
		},
	},
	// A .png extension should result in a PNG screenshot.
	'.png extension': {
		page: '/',
		screenshotConfig: {
			outputPath: `${OUTPUT_DIR}/format.png`,
		},
		expected: {
			...DEFAULT_EXPECTED,
			format: 'png',
		},
	},
	// A .jpg extension should result in a JPEG screenshot.
	'.jpg extension': {
		page: '/',
		screenshotConfig: {
			outputPath: `${OUTPUT_DIR}/format.jpg`,
		},
		expected: {
			...DEFAULT_EXPECTED,
			format: 'jpeg',
		},
	},
	// A .jpeg extension should result in a JPEG screenshot.
	'.jpeg extension': {
		page: '/',
		screenshotConfig: {
			outputPath: `${OUTPUT_DIR}/format.jpeg`,
		},
		expected: {
			...DEFAULT_EXPECTED,
			format: 'jpeg',
		},
	},
	// A .webp extension should result in a WebP screenshot.
	'.webp extension': {
		page: '/',
		screenshotConfig: {
			outputPath: `${OUTPUT_DIR}/format.webp`,
		},
		expected: {
			...DEFAULT_EXPECTED,
			format: 'webp',
		},
	},
	// A deviceScaleFactor of 2 should result in a screenshot that is twice as large.
	'deviceScaleFactor viewport option': {
		page: '/',
		screenshotConfig: {
			outputPath: `${OUTPUT_DIR}/viewport-device-scale-factor.png`,
			width: 600,
			height: 315,
			setViewportOptions: {
				deviceScaleFactor: 2,
			},
		},
		expected: DEFAULT_EXPECTED,
	},
} satisfies Record<string, FixtureImage>;
