/**
 * Definitions for every image produced by the main integration fixture build.
 *
 * Each entry describes:
 *   - which Astro page to screenshot (`page`)
 *   - the configuration to pass to the snapshot integration (`screenshotConfig`)
 *   - the properties the resulting image is expected to have (`expected`)
 *
 * @module
 */

import type sharp from 'sharp';
import type { Config } from '../packages/astro-snapshot/src/index.ts';

/** Directory (relative to the fixture project root) where all test outputs land. */
export const OUTPUT_DIR = 'output' as const;

/**
 * A color in the format `{ r: number, g: number, b: number }`.
 */
export type Color = sharp.Stats['dominant'];

export const RED: Color = {
	r: 255,
	g: 0,
	b: 0,
};

export interface ImageExpectation {
	format: string;
	width: number;
	height: number;
	color?: Color;
}

export interface FixtureImage {
	/** Astro page route to screenshot. */
	readonly page: string;
	/** Config entry passed to the snapshot integration (includes `outputPath`). */
	readonly screenshotConfig: Config['pages'][string][number];
	/** Properties the produced image is expected to have. */
	readonly expected: ImageExpectation;
}

/**
 * All images generated by the main fixture build (`astro.config.ts`).
 *
 * Keys are used as human-readable labels in test output.
 */
export const IMAGES = {
	basic: {
		page: '/',
		screenshotConfig: {
			outputPath: `${OUTPUT_DIR}/basic.png`,
		},
		expected: {
			format: 'png',
			width: 1200,
			height: 630,
			color: RED,
		},
	},
} satisfies Record<string, FixtureImage>;
